### ISSUE TITLE
Дедупликация встаёт колом :(

### ISSUE THREAD

**Issue by avoiteh** [EvilFreelancer/impruver#1]
Блин!

IlyaGusev/oasst1_ru_main_branch
README.md: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 661/661 [00:00<?, ?B/s]
c:\user\impruver\venv\lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Parser\.cache\huggingface\hub\datasets--IlyaGusev--oasst1_ru_main_branch. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
oasst1_ru_main_branch.py: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.91k/1.91k [00:00<?, ?B/s]
oasst1_ru_main_branch.jsonl: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.11M/2.11M [00:08<00:00, 253kB/s]
Generating train split:   0%|                                                                                                                                                                                | 0/614 [00:00<?, ? examples/s]
Traceback (most recent call last):
  File "c:\user\impruver\venv\lib\site-packages\datasets\builder.py", line 1607, in _prepare_split_single
    for key, record in generator:
  File "C:\Users\Parser\.cache\huggingface\modules\datasets_modules\datasets\IlyaGusev--oasst1_ru_main_branch\7f32b851c256acc6a86dc73b72689ba7e568cbf623c75a2e9c2d581c4f8cd060\oasst1_ru_main_branch.py", line 62, in _generate_examples
    for id_, line in enumerate(f):
  File "C:\Users\Parser\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 237: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\user\impruver\compose_dataset.py", line 148, in <module>
    fire.Fire(compose_dataset)
  File "c:\user\impruver\venv\lib\site-packages\fire\core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "c:\user\impruver\venv\lib\site-packages\fire\core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "c:\user\impruver\venv\lib\site-packages\fire\core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "c:\user\impruver\compose_dataset.py", line 138, in compose_dataset
    records = load_datasets(config, tokenizer, max_tokens_count)
  File "c:\user\impruver\compose_dataset.py", line 43, in load_datasets
    hf_dataset = load_dataset(dataset['name'], split=split, trust_remote_code=True)
  File "c:\user\impruver\venv\lib\site-packages\datasets\load.py", line 2154, in load_dataset
    builder_instance.download_and_prepare(
  File "c:\user\impruver\venv\lib\site-packages\datasets\builder.py", line 924, in download_and_prepare
    self._download_and_prepare(
  File "c:\user\impruver\venv\lib\site-packages\datasets\builder.py", line 1648, in _download_and_prepare
    super()._download_and_prepare(
  File "c:\user\impruver\venv\lib\site-packages\datasets\builder.py", line 1000, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "c:\user\impruver\venv\lib\site-packages\datasets\builder.py", line 1486, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "c:\user\impruver\venv\lib\site-packages\datasets\builder.py", line 1643, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset

**Comment by avoiteh** [comment]
Ошибка возникает на датасетах:
name: IlyaGusev/oasst1_ru_main_branch
и
name: lksy/ru_instruct_gpt4

Видимо это связано с тем, что я под Windows 10 ;(

**Comment by EvilFreelancer** [comment]
Привет! Проблема с тем что windows не поддерижвает символические ссылки на файлы, в чате канала https://t.me/evilfreelancer была дана рекомендация либо из под админа запустить python, либо при помощи WSL2.
